# Generated by Django 5.2.7 on 2025-10-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_communitycomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="gif_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="communitypost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community/images/"
            ),
        ),
        migrations.AlterField(
            model_name="communitypost",
            name="content",
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="reaction_type",
            field=models.CharField(
                choices=[
                    ("heart", "❤️"),
                    ("laugh", "😂"),
                    ("pray", "🙏"),
                    ("sad", "😢"),
                    ("light", "🌟"),
                ],
                max_length=10,
            ),
        ),
    ]
