# Generated by Django 5.2.7 on 2025-10-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_communitypost_gif_url_communitypost_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communitypost",
            name="gif_url",
        ),
    ]
