# Generated by Django 5.2.7 on 2025-10-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0007_remove_communitypost_gif_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitypost",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="community/videos/"
            ),
        ),
    ]
