# Generated by Django 5.2.7 on 2025-10-22 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('emotion_target', models.CharField(choices=[('calm', 'Calma'), ('anxious', 'Ansiedad'), ('sad', 'Tristeza'), ('angry', 'Enojo'), ('joyful', 'Alegría'), ('neutral', 'Neutral'), ('stressed', 'Estrés')], max_length=20)),
                ('duration_minutes', models.IntegerField(choices=[(3, '3 minutos'), (5, '5 minutos'), (10, '10 minutos'), (15, '15 minutos')])),
                ('script', models.TextField(help_text='Guión de la meditación')),
                ('audio_url', models.URLField(blank=True, help_text='URL del audio (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('emotion_target', 'duration_minutes'),
            },
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('duration_actual', models.IntegerField(blank=True, help_text='Duración real en minutos', null=True)),
                ('notes', models.TextField(blank=True)),
                ('emotion_before', models.CharField(blank=True, max_length=20)),
                ('emotion_after', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meditation.meditation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
